import { readdir, writeFile } from 'node:fs/promises';
import { extname, join, relative, sep } from 'node:path';

const mimeTypes: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.webmanifest': 'application/manifest+json; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.svg': 'image/svg+xml; charset=utf-8',
  '.png': 'image/png',
};

async function walk(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const path = join(directory, entry.name);
      return entry.isDirectory() ? walk(path) : [path];
    }),
  );
  return files.flat();
}

const files = await walk('public');
const entries = await Promise.all(
  files.map(async (path) => {
    const route = `/${relative('public', path).split(sep).join('/')}`;
    const bytes = new Uint8Array(await Bun.file(path).arrayBuffer());
    return [
      route,
      {
        body: Buffer.from(bytes).toString('base64'),
        type: mimeTypes[extname(path)] || 'application/octet-stream',
        immutable: route.startsWith('/icons/') || route.startsWith('/screenshots/'),
      },
    ] as const;
  }),
);

const source = `// Generated by scripts/embed-public.ts. Do not edit.\nexport const publicAssets = ${JSON.stringify(Object.fromEntries(entries))} as const;\n`;
await writeFile('src/public.generated.ts', source);
console.log(`Embedded ${entries.length} public assets.`);
